# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginwindow(object):
    def setupUi(self, loginwindow):
        loginwindow.setObjectName("loginwindow")
        loginwindow.resize(828, 480)
        self.formLayout = QtWidgets.QFormLayout(loginwindow)
        self.formLayout.setContentsMargins(250, 50, -1, 30)
        self.formLayout.setVerticalSpacing(100)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(31, -1, 28, -1)
        self.gridLayout.setHorizontalSpacing(23)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(loginwindow)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Assets/Icons/logo-mailer.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(loginwindow)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.frame = QtWidgets.QFrame(loginwindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setVerticalSpacing(29)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, -1, -1, -1)
        self.gridLayout_4.setHorizontalSpacing(18)
        self.gridLayout_4.setVerticalSpacing(28)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, 10, -1)
        self.gridLayout_3.setHorizontalSpacing(50)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.username = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.gridLayout_3.addWidget(self.username, 0, 0, 1, 1)
        self.username_text_box = QtWidgets.QLineEdit(self.frame)
        self.username_text_box.setObjectName("username_text_box")
        self.gridLayout_3.addWidget(self.username_text_box, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, 10, -1)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.password = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout_2.addWidget(self.password, 0, 0, 1, 1)
        self.password_text_box = QtWidgets.QLineEdit(self.frame)
        self.password_text_box.setObjectName("password_text_box")
        self.gridLayout_2.addWidget(self.password_text_box, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.forget_password = QtWidgets.QCheckBox(self.frame)
        self.forget_password.setTristate(True)
        self.forget_password.setObjectName("forget_password")
        self.gridLayout_4.addWidget(self.forget_password, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(20)
        self.splitter.setObjectName("splitter")
        self.login = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.reset = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset.setFont(font)
        self.reset.setObjectName("reset")
        self.gridLayout_5.addWidget(self.splitter, 1, 0, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frame)

        self.retranslateUi(loginwindow)
        QtCore.QMetaObject.connectSlotsByName(loginwindow)

    def retranslateUi(self, loginwindow):
        _translate = QtCore.QCoreApplication.translate
        loginwindow.setWindowTitle(_translate("loginwindow", "Login To MailerGui"))
        self.label_2.setText(_translate("loginwindow", "MailerGUI"))
        self.username.setText(_translate("loginwindow", "USERNAME"))
        self.password.setText(_translate("loginwindow", "PASSWORD"))
        self.forget_password.setText(_translate("loginwindow", "Don\'t Forget the Password"))
        self.login.setText(_translate("loginwindow", "OK"))
        self.reset.setText(_translate("loginwindow", "RESET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginwindow = QtWidgets.QDialog()
    ui = Ui_loginwindow()
    ui.setupUi(loginwindow)
    loginwindow.show()
    sys.exit(app.exec_())
