# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.test_send_button = QtWidgets.QPushButton(self.groupBox)
        self.test_send_button.setObjectName("test_send_button")
        self.gridLayout_4.addWidget(self.test_send_button, 3, 1, 1, 1)
        self.test_email_label = QtWidgets.QLineEdit(self.groupBox)
        self.test_email_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.test_email_label.setObjectName("test_email_label")
        self.gridLayout_4.addWidget(self.test_email_label, 3, 0, 1, 1)
        self.add_template_button = QtWidgets.QPushButton(self.groupBox)
        self.add_template_button.setObjectName("add_template_button")
        self.gridLayout_4.addWidget(self.add_template_button, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.edit_button = QtWidgets.QPushButton(self.groupBox)
        self.edit_button.setObjectName("edit_button")
        self.gridLayout_4.addWidget(self.edit_button, 1, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 9, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.placeholder_text = QtWidgets.QTextEdit(self.groupBox_2)
        self.placeholder_text.setPlaceholderText("")
        self.placeholder_text.setObjectName("placeholder_text")
        self.gridLayout_5.addWidget(self.placeholder_text, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 7, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(23)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.attachment_button = QtWidgets.QPushButton(self.centralwidget)
        self.attachment_button.setObjectName("attachment_button")
        self.gridLayout_3.addWidget(self.attachment_button, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.attachment_label = QtWidgets.QLineEdit(self.centralwidget)
        self.attachment_label.setReadOnly(True)
        self.attachment_label.setObjectName("attachment_label")
        self.gridLayout_3.addWidget(self.attachment_label, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 8, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(39)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subject_text = QtWidgets.QLineEdit(self.centralwidget)
        self.subject_text.setMaxLength(100000)
        self.subject_text.setObjectName("subject_text")
        self.gridLayout_2.addWidget(self.subject_text, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 11, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(12, -1, 12, -1)
        self.gridLayout_7.setHorizontalSpacing(62)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.download_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.gridLayout_7.addWidget(self.download_button, 2, 0, 1, 1)
        self.send_bulk_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.send_bulk_button.setObjectName("send_bulk_button")
        self.gridLayout_7.addWidget(self.send_bulk_button, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 10, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(23)
        self.gridLayout.setObjectName("gridLayout")
        self.extract_button = QtWidgets.QPushButton(self.centralwidget)
        self.extract_button.setObjectName("extract_button")
        self.gridLayout.addWidget(self.extract_button, 0, 2, 1, 1)
        self.recipients_label = QtWidgets.QLineEdit(self.centralwidget)
        self.recipients_label.setMouseTracking(False)
        self.recipients_label.setReadOnly(True)
        self.recipients_label.setObjectName("recipients_label")
        self.gridLayout.addWidget(self.recipients_label, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.view_button = QtWidgets.QPushButton(self.centralwidget)
        self.view_button.setObjectName("view_button")
        self.gridLayout.addWidget(self.view_button, 0, 5, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 916, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuDownload = QtWidgets.QMenu(self.menuBar)
        self.menuDownload.setObjectName("menuDownload")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSample_Recipient = QtWidgets.QAction(MainWindow)
        self.actionSample_Recipient.setObjectName("actionSample_Recipient")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionSettings)
        self.menuDownload.addSeparator()
        self.menuDownload.addAction(self.actionSample_Recipient)
        self.menuDownload.addAction(self.actionLogs)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuDownload.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MailerGui"))
        self.groupBox.setTitle(_translate("MainWindow", "Template"))
        self.test_send_button.setText(_translate("MainWindow", "Send Test"))
        self.test_email_label.setPlaceholderText(_translate("MainWindow", "Add test email"))
        self.add_template_button.setText(_translate("MainWindow", "Add"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Template file name will be displayed here"))
        self.edit_button.setText(_translate("MainWindow", "View"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Placeholder"))
        self.placeholder_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">{</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">    &quot;key1&quot; : &quot;value1&quot;,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">    &quot;key2&quot; : &quot;value2&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">    </span></p></body></html>"))
        self.attachment_button.setText(_translate("MainWindow", "Attach"))
        self.label_7.setText(_translate("MainWindow", "Attachment     "))
        self.attachment_label.setPlaceholderText(_translate("MainWindow", "File name will be displayed here"))
        self.subject_text.setPlaceholderText(_translate("MainWindow", "Add Subject here"))
        self.label_4.setText(_translate("MainWindow", "Add Subject"))
        self.download_button.setText(_translate("MainWindow", "Download logs"))
        self.send_bulk_button.setText(_translate("MainWindow", "Send Bulk Mail"))
        self.extract_button.setText(_translate("MainWindow", "Import"))
        self.recipients_label.setPlaceholderText(_translate("MainWindow", "File name will be displayed here"))
        self.label_6.setText(_translate("MainWindow", "Add Recipients"))
        self.view_button.setText(_translate("MainWindow", "View "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download"))
        self.actionSample_Recipient.setText(_translate("MainWindow", "Sample Recipient"))
        self.actionSample_Recipient.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLogs.setText(_translate("MainWindow", "Logs"))
        self.actionLogs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
