# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 483)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(400, -1, 9, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setObjectName("accept_button")
        self.gridLayout_3.addWidget(self.accept_button, 0, 0, 1, 1)
        self.apply_button = QtWidgets.QPushButton(Dialog)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout_3.addWidget(self.apply_button, 0, 1, 1, 1)
        self.reset_button = QtWidgets.QPushButton(Dialog)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout_3.addWidget(self.reset_button, 0, 2, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.gridLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 26, -1, 72)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.password_setting = QtWidgets.QLineEdit(Dialog)
        self.password_setting.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_setting.setObjectName("password_setting")
        self.gridLayout.addWidget(self.password_setting, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.username_Setting = QtWidgets.QLineEdit(Dialog)
        self.username_Setting.setObjectName("username_Setting")
        self.gridLayout.addWidget(self.username_Setting, 0, 1, 1, 1)
        self.api_key_setting = QtWidgets.QLineEdit(Dialog)
        self.api_key_setting.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.api_key_setting.setObjectName("api_key_setting")
        self.gridLayout.addWidget(self.api_key_setting, 6, 1, 1, 1)
        self.mail_domain_setting = QtWidgets.QLineEdit(Dialog)
        self.mail_domain_setting.setObjectName("mail_domain_setting")
        self.gridLayout.addWidget(self.mail_domain_setting, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.logs_dir_setting = QtWidgets.QLineEdit(Dialog)
        self.logs_dir_setting.setObjectName("logs_dir_setting")
        self.gridLayout_2.addWidget(self.logs_dir_setting, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.accept_button.setText(_translate("Dialog", "Ok"))
        self.apply_button.setText(_translate("Dialog", "Apply"))
        self.reset_button.setText(_translate("Dialog", "Reset"))
        self.label_7.setText(_translate("Dialog", "Change Password"))
        self.label_6.setText(_translate("Dialog", "Enter mail domain name"))
        self.label_9.setText(_translate("Dialog", "Enter apikey"))
        self.label.setText(_translate("Dialog", "Change Username"))
        self.label_8.setText(_translate("Dialog", "Change logs directory "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
